name: Docker

on:
  push:
    branches:
      - go-version-ci-test
  pull_request:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: hexlet-basics/exercises-action@release
        with:
          DOCKER_USERNAME: "username"
          DOCKER_PASSWORD: "12345"
